baseurl = "http://lockedata.uk/"
languageCode = "en-gb"
title = "Locke Data"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "basiclocke"


[params]
  avatar = "profile.png"
  author = "Locke Data"
  description = "Locke Data is a consultancy that helps people and organisations get started with data science. We offer training, advice, and technical leadership to make sure things go more smoothly. Find out more about us on our core site [itsalocke.com](https://itsalocke.com)."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Home          = "//itsalocke.com"
  Github        = "lockedata"
  Email         = "contact@itsalocke.com"
  Twitter       = "lockedata"
  Linkedin      ="11032752"
  
