baseurl = "https://itsalocke.com/talks/"
languageCode = "en-gb"
title = "Locke Data Talks"
# Enable comments by entering your Disqus shortname
disqusShortname = "itsalocke"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-58415537-1"
theme = "hugo-lockedata-blog"

[permalinks]
  posts = "/:title/"
  page                = "/:title/"

[taxonomies]
    tag                 = "tags"
    category            = "categories"
	status              = "statuses"
	
[[languages.en.menu.prepend]]
    name                = "Locke Data"
    weight              = 1
    url                 = "https://itsalocke.com"

[[languages.en.menu.prepend]]
    name                = "Talks"
    weight              = 3
    url                 = "https://itsalocke.com/talks"
	
 # Footer
  [params.footer]
    enable = true

  [[languages.en.menu.social]]
    weight = 10
    name = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "#"
  [[languages.en.menu.social]]
    weight = 20
    name = "facebook"
    pre = "<i class='fa fa-facebook'></i>"
    url = "#"
  [[languages.en.menu.social]]
    weight = 30
    name = "linkedin"
    pre = "<i class='fa fa-linkedin'></i>"
    url = "#"
  [[languages.en.menu.footer]]
    weight = 20
    name = "Legalese and stuff"
    url = "https://itsalocke.com/company/policies"
  [[languages.en.menu.footer]]
    weight = 10
    name = "RSS"
    url = "index.xml"
  [[languages.en.menu.footer]]
    weight = 30
    name = "Bug Bounty"
    url = "https://goo.gl/forms/KQiYR201Fcn4k9Zh2"
[params]
    keywords            = ["default", "keywords", "if", "no", "front", "matter"]
  author = "Locke Data"
    description         = "Locke Data helps organisations get started with data science. Increase your skills and stay up to date by catching up on our presentations."
  dateformat = "Jan 2, 2006" # Optional
    google_analytics    = "UA-58415537-1"
    google_adsense      = "ca-pub-XXXXXX"
    disqus              = "itsalocke"
    google_webmaster    = ""
    bing_webmaster      = ""
    alexa               = ""
    favicon             = ""
copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.'

  [params.navigation]
    # Optional brand logo used in nav stored in 'static/img/'.
    logo = "LockeDataTextNew.svg"
	
# Social media icons and links that appear in the footer
[social]
    twitter             = "https://www.twitter.com/NAME_HERE"
    googleplus          = ""
    linkedin            = "https://www.linkedin.com/in/NAME_HERE"
    youtube             = "https://www.youtube.com/users/NAME_HERE"
    paypal              = ""
    instagram           = ""
    reddit              = ""
    email               = ""
    pinterest           = ""
    wordpress           = ""
